name: Debug Repository Structure

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug: List files and folders
      - name: Debug: List repository contents
        run: ls -R
